name: Hello World

on: push

jobs: 
  build:
   runs-on: ubuntu-latest

   steps: 
   
    - name: action checkout
    - uses: actions/checkout@v4
    - name: run a sample hello world Workflow
      run: echo "Hi! this workflow runs sucessfully"
